name: we_work
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.2.1
  auto_route: ^3.1.0
  salomon_bottom_bar: ^3.1.0
  flutter_svg: ^0.23.0+1
  dio: ^4.0.1
  line_awesome_flutter: ^2.0.0
  hydrated_bloc: ^7.1.0
  freezed: ^0.15.1+1
  freezed_annotation: ^0.15.0
  carousel_slider: ^4.0.0
  intro_slider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.5.0
  auto_route_generator: ^3.1.0
  build_runner: ^2.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
